In [124]:
import numpy as np
scaled_data = [11,12,13,14,15,16,17,18,19,20,21]
time_step = 4 

In [125]:
X, y = [], []

In [126]:
len(scaled_data)
scaled_data = np.array(scaled_data)
scaled_data

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [127]:
scaled_data.shape

(11,)

In [128]:
len(scaled_data)

11

In [130]:
scaled_data = scaled_data.reshape(-1,1) # creates column vector, N row 1 columns

In [131]:
scaled_data

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21]])

In [132]:
scaled_data.shape # signifies 7 rows and 1 column 

(11, 1)

In [133]:
for i in range(len(scaled_data) - time_step - 1):
    print(i)
    X.append(scaled_data[i:(i + time_step),0])
    y.append(scaled_data[i + time_step, 0])   

0
1
2
3
4
5


In [134]:
X

[array([11, 12, 13, 14]),
 array([12, 13, 14, 15]),
 array([13, 14, 15, 16]),
 array([14, 15, 16, 17]),
 array([15, 16, 17, 18]),
 array([16, 17, 18, 19])]

In [135]:
len(X)

6

In [136]:
X = np.array(X)

In [137]:
X

array([[11, 12, 13, 14],
       [12, 13, 14, 15],
       [13, 14, 15, 16],
       [14, 15, 16, 17],
       [15, 16, 17, 18],
       [16, 17, 18, 19]])

In [142]:
X.shape

(6, 4)

In [139]:
y = np.array(y)
y.shape

(6,)

In [140]:
y

array([15, 16, 17, 18, 19, 20])